### PR TITLE
Replace Node 0.10 with 7 in travis config

### PR DESCRIPTION
**Pull request by mischah**
:octocat:

### CODE REVIEW

**Comment by mischah** [comment]
Oops. Doesn’t build with node 0.12 because of:

```
> xo && ava
/home/travis/build/sindresorhus/semver-truncate/node_modules/xo/cli.js:4
const debug = require('debug')('xo');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Test failed.  See above for more details.
```

**Comment by mischah** [comment]
Would you like to get rid of `0.12.0` as well?

**Comment by sindresorhus** [comment]
Thanks, but I don't test on non-LTS Node.js versions for smaller modules. Too much churn. I'll drop older Node.js here myself when I'm ready. Thanks though.

**Comment by mischah** [comment]
:ok_hand:

**Pull request closed without merging**
